[package]
name = "entities"
version = "0.1.0"
edition = "2024"

[lib]
name = "entities"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
sea-orm = { version = "1.1.4", features = [
    "sqlx-mysql",
    "runtime-actix-native-tls",
] }
