name: Data Continuous Deployment

on:
  repository_dispatch:
    types: [deploy-data]

jobs:
  deploy:
    name: Deploy Data to Production Database
    permissions:
      contents: read
      id-token: write # Required for OIDC authentication with AWS
    runs-on: ubuntu-latest

    env:
      DEVOPS_DIRECTORY: devops
      DEVOPS_NODE_CACHE_PATH: devops/package-lock.json
      DEVOPS_NODE_VERSION_FILE: devops/package.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ${{ env.DEVOPS_NODE_VERSION_FILE }}
          cache-dependency-path: ${{ env.DEVOPS_NODE_CACHE_PATH }}
          cache: npm

      - name: Install npm Dependencies
        working-directory: ${{ env.DEVOPS_DIRECTORY }}
        run: npm ci --no-audit

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Data to Production
        working-directory: ${{ env.DEVOPS_DIRECTORY }}
        run: npm run deploy:data
